-- Seed data for Bar Tracker
-- Default admin user: username=admin, password=Admin123!

-- Insert default admin user (password: Admin123!)
INSERT INTO users (username, email, password_hash, full_name, role)
VALUES (
  'admin',
  'admin@bar.local',
  '$2a$10$rF8ZYQhqJKYxJXKxKxKxKO7YqYqYqYqYqYqYqYqYqYqYqYqYqYqYq', -- This is a placeholder, will be generated properly
  'System Administrator',
  'admin'
) ON CONFLICT (username) DO NOTHING;

-- Note: You should change the admin password immediately after first login!
-- The actual password hash will be generated by the application when you create users through the API
